name: Build and test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  check:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]
        include:
          - os: ubuntu-latest
            rust: nightly
          - os: ubuntu-latest
            rust: beta
          - os: ubuntu-latest
            rust: 1.88.0
    steps:
      - uses: actions/checkout@v6
      - uses: amqp-rs/actions/windows-setup-tls-env@main
      - uses: amqp-rs/actions/build@main
        with:
          rust: ${{ matrix.rust }}
          test: 'false'

  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    services:
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672:5672
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly, beta, stable, 1.88.0]
    steps:
      - uses: actions/checkout@v6
      - uses: amqp-rs/actions/build@main
        with:
          rust: ${{ matrix.rust }}
          check: 'false'
