name: Semver compliance check

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:

jobs:
  semver_check:
    runs-on: ubuntu-latest
    steps:
      - uses: amqp-rs/actions/checkout@main
      - uses: amqp-rs/actions/semver@main
